[functions]
  directory = "api"

[build]
  command = "make build"
  functions = "api"
[build.environment]
  GOBIN = "/opt/build/repo/api"
[template.environment]
  GO_IMPORT_PATH = "github.com/AkashRajpurohit/xml2json"

[[redirects]]
  from = "/"
  to = "https://www.youtube.com/watch?v=dQw4w9WgXcQ" # Rick Roll

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = false
  headers = { Access-Control-Allow-Origin = "*" }